// Copyright TSAV. All Rights Reserved.

#pragma once

#include "TSAVMediaSurfaceActor.h"

#include "TSAVLEDWall.generated.h"

class UHierarchicalInstancedStaticMeshComponent;
class UMaterialInterface;
class UProceduralMeshComponent;
class UStaticMeshComponent;
class UTSAVLEDPanelDefinition;

UENUM(BlueprintType)
enum class ETSAVLEDLinkPattern : uint8
{
	RowsLeftToRight UMETA(DisplayName = "Rows: Left to Right"),
	RowsSerpentine UMETA(DisplayName = "Rows: Serpentine"),
};

/** Optional cut-out applied to one cabinet face in the generated wall. */
UENUM(BlueprintType)
enum class ETSAVLEDPanelEdgeStyle : uint8
{
	Square UMETA(DisplayName = "Square"),
	DiagonalTopLeft UMETA(DisplayName = "Diagonal: Top Left"),
	DiagonalTopRight UMETA(DisplayName = "Diagonal: Top Right"),
	DiagonalBottomLeft UMETA(DisplayName = "Diagonal: Bottom Left"),
	DiagonalBottomRight UMETA(DisplayName = "Diagonal: Bottom Right"),
	RoundTopLeft UMETA(DisplayName = "Round: Top Left"),
	RoundTopRight UMETA(DisplayName = "Round: Top Right"),
	RoundBottomLeft UMETA(DisplayName = "Round: Bottom Left"),
	RoundBottomRight UMETA(DisplayName = "Round: Bottom Right"),
	Disabled UMETA(DisplayName = "Disabled / Empty"),
};

/** Read-only cabinet topology record generated by the wall configurator. */
USTRUCT(BlueprintType)
struct TSAVLEDTOOLS_API FTSAVLEDPanelLink
{
	GENERATED_BODY()

	/** Signal-chain order, starting at one. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Link")
	int32 LinkIndex = 1;

	/** Cabinet column/row in the configured wall, with (0,0) at top-left. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Link")
	FIntPoint GridPosition = FIntPoint::ZeroValue;

	/** Top-left cabinet pixel on the full processor canvas. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Link")
	FIntPoint CanvasPixelPosition = FIntPoint::ZeroValue;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Link")
	FIntPoint CabinetResolution = FIntPoint(1, 1);

	/** Derived absolute yaw assigned to this cabinet's column. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Link")
	float ColumnAngleDegrees = 0.0f;

	/** Derived absolute pitch assigned to this cabinet's row. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Link")
	float RowAngleDegrees = 0.0f;

	/** Face cut-out selected for this cabinet in the builder grid. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Link")
	ETSAVLEDPanelEdgeStyle EdgeStyle = ETSAVLEDPanelEdgeStyle::Square;
};

/**
 * Parametric LED wall builder. The video surface remains continuous across the
 * whole wall while physical panel seams, cabinet backing, and border geometry
 * are generated from the row and column settings.
 */
UCLASS(Blueprintable, meta = (DisplayName = "TSAV LED Wall Builder"))
class TSAVLEDTOOLS_API ATSAVLEDWall : public ATSAVMediaSurfaceActor
{
	GENERATED_BODY()

public:
	ATSAVLEDWall();

	/** Cabinet specification linked into every position in this wall. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "TSAV LED|Wall")
	TObjectPtr<UTSAVLEDPanelDefinition> PanelDefinition;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "TSAV LED|Wall")
	bool bUsePanelDefinition = false;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "TSAV LED|Wall", meta = (ClampMin = "1", ClampMax = "64", UIMin = "1", UIMax = "24"))
	int32 Columns = 8;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "TSAV LED|Wall", meta = (ClampMin = "1", ClampMax = "64", UIMin = "1", UIMax = "16"))
	int32 Rows = 4;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "TSAV LED|Wall", meta = (ClampMin = "10.0", UIMin = "25.0", UIMax = "200.0", EditCondition = "!bUsePanelDefinition"))
	float PanelWidthCm = 50.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "TSAV LED|Wall", meta = (ClampMin = "10.0", UIMin = "25.0", UIMax = "200.0", EditCondition = "!bUsePanelDefinition"))
	float PanelHeightCm = 50.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "TSAV LED|Pixels", meta = (ClampMin = "1", EditCondition = "!bUsePanelDefinition"))
	int32 PanelResolutionX = 128;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "TSAV LED|Pixels", meta = (ClampMin = "1", EditCondition = "!bUsePanelDefinition"))
	int32 PanelResolutionY = 128;

	/** Clearance between cabinet bodies behind the continuous front video surface. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "TSAV LED|Wall", meta = (ClampMin = "0.0", UIMin = "0.0", UIMax = "5.0"))
	float PanelGapCm = 0.5f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "TSAV LED|Wall", meta = (ClampMin = "1.0", UIMin = "2.0", UIMax = "40.0"))
	float WallDepthCm = 12.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "TSAV LED|Wall", meta = (ClampMin = "0.0", UIMin = "0.0", UIMax = "15.0"))
	float BorderCm = 2.0f;

	/** Show the generated cabinet seams on top of the continuous video surface. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "TSAV LED|Wall")
	bool bShowPanelSeams = true;

	/** Bend at each seam (column N to N+1), clamped to -90..90 degrees in 0.5 degree steps. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "TSAV LED|Shape", meta = (ClampMin = "-90.0", ClampMax = "90.0"))
	TArray<float> ColumnSeamAnglesDegrees;

	/** Bend at each horizontal seam (row N to N+1), clamped to -90..90 degrees in 0.5 degree steps. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "TSAV LED|Shape", meta = (ClampMin = "-90.0", ClampMax = "90.0"))
	TArray<float> RowSeamAnglesDegrees;

	/** Legacy absolute column headings retained only to migrate walls created by the initial implementation. */
	UPROPERTY(meta = (DeprecatedProperty, DeprecationMessage = "Use ColumnSeamAnglesDegrees."))
	TArray<float> ColumnAnglesDegrees;

	/** Row-major panel face styles. Index = Row * Columns + Column. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "TSAV LED|Shape")
	TArray<ETSAVLEDPanelEdgeStyle> PanelEdgeStyles;

	/** Cabinet signal/topology ordering shown in Generated Panel Links. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "TSAV LED|Topology")
	ETSAVLEDLinkPattern LinkPattern = ETSAVLEDLinkPattern::RowsSerpentine;

	/** Generated cabinet link order and exact processor-canvas coordinates. */
	UPROPERTY(VisibleInstanceOnly, BlueprintReadOnly, Category = "TSAV LED|Topology")
	TArray<FTSAVLEDPanelLink> PanelLinks;

	/** Force an immediate geometry and topology refresh in the editor. */
	UFUNCTION(BlueprintCallable, CallInEditor, Category = "TSAV LED|Topology")
	void RebuildPanelLayout();

	UFUNCTION(BlueprintPure, Category = "TSAV LED|Wall")
	float GetWallWidthCm() const;

	UFUNCTION(BlueprintPure, Category = "TSAV LED|Wall")
	float GetWallHeightCm() const;

	UFUNCTION(BlueprintPure, Category = "TSAV LED|Pixels")
	FIntPoint GetWallResolutionPixels() const;

	UFUNCTION(BlueprintPure, Category = "TSAV LED|Pixels")
	FVector2D GetPanelPixelPitchMm() const;

	UFUNCTION(BlueprintPure, Category = "TSAV LED|Shape")
	float GetColumnAngleDegrees(int32 Column) const;

	UFUNCTION(BlueprintPure, Category = "TSAV LED|Shape")
	float GetRowAngleDegrees(int32 Row) const;

	UFUNCTION(BlueprintPure, Category = "TSAV LED|Shape")
	ETSAVLEDPanelEdgeStyle GetPanelEdgeStyle(int32 Column, int32 Row) const;

	/** False when this grid position is intentionally empty. */
	UFUNCTION(BlueprintPure, Category = "TSAV LED|Shape")
	bool IsPanelEnabled(int32 Column, int32 Row) const;

protected:
	virtual void OnConstruction(const FTransform& Transform) override;
	virtual void OnDisplayMaterialUpdated(UMaterialInterface* AppliedMaterial) override;

private:
	virtual FIntPoint GetNativePixelResolution() const override;
	void BuildColumnTransforms(TArray<FVector>& OutFrontCenters, TArray<float>& OutYawDegrees) const;
	void BuildRowTransforms(TArray<FVector>& OutFrontCenters, TArray<float>& OutPitchDegrees) const;
	void UpdateGeometry();
	void UpdatePanelLinks();
	void NormalizeShapeSettings();
	float GetEffectivePanelWidthCm() const;
	float GetEffectivePanelHeightCm() const;
	float GetEffectivePanelDepthCm() const;
	float GetEffectiveBorderCm() const;
	FIntPoint GetEffectivePanelResolution() const;
	void SetBox(UStaticMeshComponent* Component, const FVector& SizeCm, const FVector& LocationCm) const;

	UPROPERTY(VisibleAnywhere, Category = "TSAV LED|Components")
	TObjectPtr<UStaticMeshComponent> Backing;

	UPROPERTY(VisibleAnywhere, Category = "TSAV LED|Components")
	TObjectPtr<UStaticMeshComponent> TopBorder;

	UPROPERTY(VisibleAnywhere, Category = "TSAV LED|Components")
	TObjectPtr<UStaticMeshComponent> BottomBorder;

	UPROPERTY(VisibleAnywhere, Category = "TSAV LED|Components")
	TObjectPtr<UStaticMeshComponent> LeftBorder;

	UPROPERTY(VisibleAnywhere, Category = "TSAV LED|Components")
	TObjectPtr<UStaticMeshComponent> RightBorder;

	UPROPERTY(VisibleAnywhere, Category = "TSAV LED|Components")
	TObjectPtr<UHierarchicalInstancedStaticMeshComponent> PanelSeams;

	/** Generated, individually shaped cabinet faces and curved cabinet bodies. */
	UPROPERTY(VisibleAnywhere, Category = "TSAV LED|Components")
	TObjectPtr<UProceduralMeshComponent> ShapedWallMesh;
};
