// Copyright TSAV. All Rights Reserved.

#pragma once

#include "TSAVMediaSurfaceActor.h"

#include "TSAVLEDWall.generated.h"

class UHierarchicalInstancedStaticMeshComponent;
class UStaticMeshComponent;
class UTSAVLEDPanelDefinition;

UENUM(BlueprintType)
enum class ETSAVLEDLinkPattern : uint8
{
	RowsLeftToRight UMETA(DisplayName = "Rows: Left to Right"),
	RowsSerpentine UMETA(DisplayName = "Rows: Serpentine"),
};

/** Read-only cabinet topology record generated by the wall configurator. */
USTRUCT(BlueprintType)
struct TSAVLEDTOOLS_API FTSAVLEDPanelLink
{
	GENERATED_BODY()

	/** Signal-chain order, starting at one. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Link")
	int32 LinkIndex = 1;

	/** Cabinet column/row in the configured wall, with (0,0) at top-left. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Link")
	FIntPoint GridPosition = FIntPoint::ZeroValue;

	/** Top-left cabinet pixel on the full processor canvas. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Link")
	FIntPoint CanvasPixelPosition = FIntPoint::ZeroValue;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Link")
	FIntPoint CabinetResolution = FIntPoint(1, 1);
};

/**
 * Parametric LED wall builder. The video surface remains continuous across the
 * whole wall while physical panel seams, cabinet backing, and border geometry
 * are generated from the row and column settings.
 */
UCLASS(Blueprintable, meta = (DisplayName = "TSAV LED Wall Builder"))
class TSAVLEDTOOLS_API ATSAVLEDWall : public ATSAVMediaSurfaceActor
{
	GENERATED_BODY()

public:
	ATSAVLEDWall();

	/** Cabinet specification linked into every position in this wall. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "TSAV LED|Wall")
	TObjectPtr<UTSAVLEDPanelDefinition> PanelDefinition;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "TSAV LED|Wall")
	bool bUsePanelDefinition = false;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "TSAV LED|Wall", meta = (ClampMin = "1", ClampMax = "64", UIMin = "1", UIMax = "24"))
	int32 Columns = 8;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "TSAV LED|Wall", meta = (ClampMin = "1", ClampMax = "64", UIMin = "1", UIMax = "16"))
	int32 Rows = 4;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "TSAV LED|Wall", meta = (ClampMin = "10.0", UIMin = "25.0", UIMax = "200.0", EditCondition = "!bUsePanelDefinition"))
	float PanelWidthCm = 50.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "TSAV LED|Wall", meta = (ClampMin = "10.0", UIMin = "25.0", UIMax = "200.0", EditCondition = "!bUsePanelDefinition"))
	float PanelHeightCm = 50.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "TSAV LED|Pixels", meta = (ClampMin = "1", EditCondition = "!bUsePanelDefinition"))
	int32 PanelResolutionX = 128;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "TSAV LED|Pixels", meta = (ClampMin = "1", EditCondition = "!bUsePanelDefinition"))
	int32 PanelResolutionY = 128;

	/** Visible space/seam between adjacent cabinets. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "TSAV LED|Wall", meta = (ClampMin = "0.0", UIMin = "0.0", UIMax = "5.0"))
	float PanelGapCm = 0.5f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "TSAV LED|Wall", meta = (ClampMin = "1.0", UIMin = "2.0", UIMax = "40.0"))
	float WallDepthCm = 12.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "TSAV LED|Wall", meta = (ClampMin = "0.0", UIMin = "0.0", UIMax = "15.0"))
	float BorderCm = 2.0f;

	/** Show the generated cabinet seams on top of the continuous video surface. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "TSAV LED|Wall")
	bool bShowPanelSeams = true;

	/** Cabinet signal/topology ordering shown in Generated Panel Links. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "TSAV LED|Topology")
	ETSAVLEDLinkPattern LinkPattern = ETSAVLEDLinkPattern::RowsSerpentine;

	/** Generated cabinet link order and exact processor-canvas coordinates. */
	UPROPERTY(VisibleInstanceOnly, BlueprintReadOnly, Category = "TSAV LED|Topology")
	TArray<FTSAVLEDPanelLink> PanelLinks;

	/** Force an immediate geometry and topology refresh in the editor. */
	UFUNCTION(BlueprintCallable, CallInEditor, Category = "TSAV LED|Topology")
	void RebuildPanelLayout();

	UFUNCTION(BlueprintPure, Category = "TSAV LED|Wall")
	float GetWallWidthCm() const;

	UFUNCTION(BlueprintPure, Category = "TSAV LED|Wall")
	float GetWallHeightCm() const;

	UFUNCTION(BlueprintPure, Category = "TSAV LED|Pixels")
	FIntPoint GetWallResolutionPixels() const;

	UFUNCTION(BlueprintPure, Category = "TSAV LED|Pixels")
	FVector2D GetPanelPixelPitchMm() const;

protected:
	virtual void OnConstruction(const FTransform& Transform) override;

private:
	virtual FIntPoint GetNativePixelResolution() const override;
	void UpdateGeometry();
	void UpdatePanelLinks();
	float GetEffectivePanelWidthCm() const;
	float GetEffectivePanelHeightCm() const;
	float GetEffectivePanelDepthCm() const;
	float GetEffectiveBorderCm() const;
	FIntPoint GetEffectivePanelResolution() const;
	void SetBox(UStaticMeshComponent* Component, const FVector& SizeCm, const FVector& LocationCm) const;

	UPROPERTY(VisibleAnywhere, Category = "TSAV LED|Components")
	TObjectPtr<UStaticMeshComponent> Backing;

	UPROPERTY(VisibleAnywhere, Category = "TSAV LED|Components")
	TObjectPtr<UStaticMeshComponent> TopBorder;

	UPROPERTY(VisibleAnywhere, Category = "TSAV LED|Components")
	TObjectPtr<UStaticMeshComponent> BottomBorder;

	UPROPERTY(VisibleAnywhere, Category = "TSAV LED|Components")
	TObjectPtr<UStaticMeshComponent> LeftBorder;

	UPROPERTY(VisibleAnywhere, Category = "TSAV LED|Components")
	TObjectPtr<UStaticMeshComponent> RightBorder;

	UPROPERTY(VisibleAnywhere, Category = "TSAV LED|Components")
	TObjectPtr<UHierarchicalInstancedStaticMeshComponent> PanelSeams;
};
